-- Criar produtos

INSERT INTO products (name, description, price, image_path) VALUES 
('Açaí', 'Um açaí top de qualidade duvidosa, o qual pode te deixar com dor de barriga', 18, ''),
('Blusa', 'Uma blusa pra vc', 35.50, ''),
('Jeans', 'Uma jeans de mendigo para você conquistar as gatinhas', 70.50,''),
('Moletom', 'Um moletom de otaku virgem', 199.90,''),
('Sorvete', 'Sorvete pra te fazer ficar gripado', 10, ''),
('Action Figure', 'Uma action figure de otaku virjão', 200, ''),
('Rexona', 'Ele nunca te abandona, sua mulher sim', 18, ''),
('Tenys Pe', 'Pra tirar seu chulé desgraçado', 16,''),
('Jogos', 'Sei lá, são jogos pra gente esquisita', 13.59, ''),
('Xadrez', 'Jogo para você que é burro e quer ficar inteligente', 24.69, ''),
('Smartphone', 'Um telefone pra vc postar merda no twitter', 1499.99, ''),
('Nokia Tijolão', 'Pode usar pra bater em alguem', 69, ''),
('Coquinha 2L', 'Huuummm coquinha', 12, ''),
('Coquinha 1L', 'Uma coquinha, só que menor', 8, ''),
('Monitor', 'Um monitor', 799.99, ''),
('Chaveiro', 'Chaveiro pra vc carregar chaves', 1, '');

INSERT INTO news (title, text, image_path, created_at_utc) VALUES 
('Matéria 1', 'É uma matéria ne vey.É uma matéria ne vey.É uma matéria ne vey.É uma matéria ne vey.É uma matéria ne vey.', '', '2022-11-05T22:47:00'),
('Esta é outra matéria', 'Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.Ih ala, um corno lendo a matéria kkkkk.', '', '2022-11-05T22:48:00'),
('Então, amigos são flagrados bicudos', 'Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.Dois sujeitos foram flagrados se embebando em algum lugar, eu to com preguiça.', '', '2022-11-05T22:49:00'),
('Já viu esses caras, eles deram cirrose', 'Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.Problema deles, não meu.', '', '2022-11-05T22:49:00'),
('Conheça a incrível história do menino cego que enxergava', 'Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.Ele era cego a noite, mas de dia para encobrir seu disfarce, ele era conhecido como Vinicius.', '', '2022-11-05T13:50:00'),
('Outra matéria diferente da primeira', 'Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.Então, não sei o que escrever.', '', '2022-11-05T22:51:00'),
('Menino da 191 é flagrado dando selinho em outro homem', 'O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.O menino conhecido como PH, foi flagrado dando selinho em um garoto do médio, ele também é do médio.', '', '2022-11-05T04:52:00'),
('The Last Dance tem data confirmada', 'Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.Algum dia e em algum lugar.', '', '2022-11-05T22:55:00'),
('To com preguiça', 'Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.Tô com preguiça.', '', '2022-11-05T23:55:00'),
('Pelé morre e deixa herança pro filho drogado', 'O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.O cara é drogado né.', '', '2022-11-05T20:30:00'),
('Brasil se torna hexa campeão', 'Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.Somos felizes novamente, SOMOS FELIZES, MENINO NEY ARRASOU, NUNCA DUVIDAMOS DELE.', '', '2022-11-05T22:15:00'),
('Lula é ladrão e bolsonaro também', 'Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.Ladrões.', '', '2022-11-05T21:12:00');